### ISSUE TITLE
Preserve layout options for blocks when mirroring

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/MirrorExhibitPage#1]
Currently the layout options (e.g. image size, position, etc.) don't seem to be respected in mirrored page.

Compare, for example, this [original page of the Tower of London](http://omeka-dev.carleton.edu/omeka/exhibits/show/castles/toweroflondon) with [this mirrored version](http://omeka-dev.carleton.edu/omeka/exhibits/show/testmirror/mirrored)

**Comment by apjmason** [comment]
Seems like this is a result of nested exhibit-block divs breaking the css rules, since the mirror wraps the original page's ones , e.g. 

```
<div class="exhibit-block layout-mirror"> 
  <div class="exhibit-block layout-file-text">
```

Might need to add layout.css as in [SliderExhibitLayout](https://github.com/DigitalCarleton/SliderExhibitLayout/blob/master/views/shared/exhibit_layouts/slider/layout.css)?

**Comment by padillac** [comment]
Adding layout.css (for all ExhibitBuilder layouts) as suggested and tweaking layout.php to remove page block nesting has resolved the issue.

See original example: [original page of the Tower of London](http://omeka-dev.carleton.edu/omeka/exhibits/show/castles/toweroflondon) with [this mirrored version](http://omeka-dev.carleton.edu/omeka/exhibits/show/testmirror/mirrored)
