### ISSUE TITLE
Breaks Edit Link plugin functionality 

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/MirrorExhibitPage#2]
With [plugin Edit Link](https://github.com/omeka/plugin-EditLink/blob/master/EditLinkPlugin.php) enabled, expected action yields 404 error on both original and mirrored page.

**Comment by padillac** [comment]
I was not able to reproduce this either on MAMP or on omeka-dev (religionsmn). Edit link worked correctly. Perhaps it has been resolved by another change?  Is there an example of a page where it is still broken?

**Comment by apjmason** [comment]
Not able to reproduce.
