### ISSUE TITLE
Replace slug with exhibit title in form select

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/MirrorExhibitPage#3]
A cosmetic fix, but the dropdown values would be more human readable if they used the "title" value instead of the URL "slug" to populate the drop down menu.

https://github.com/DigitalCarleton/MirrorExhibitPage/blob/0e531316a0a08b9daf28493ba9ee74a235c575c4/views/shared/exhibit_layouts/mirror/form.php#L20

**Comment by padillac** [comment]
Fixed! 
I added a jquery script to store and access the slug value from within the dropdown option element, because the slug is needed to display the correct page tiles, but the displayed dropdown values are now titles.
